### ISSUE TITLE
Failed to build in Mac OS

### ISSUE THREAD

**Issue by alexcdever** [shirou/gopsutil#1040] opened 2021-02-25 14:33 UTC
**Describe the bug**
I am writing a cmd tool, I need it to collect OS info, but failed to build.
error message:
```
# github.com/shirou/gopsutil/host
../../.gvm/pkgsets/go1.16/global/pkg/mod/github.com/shirou/gopsutil@v3.21.1+incompatible/host/host_bsd.go:20:13: undefined: unix.SysctlTimeval
```

**To Reproduce**
```go
package cmd

import (
	"fmt"
	"github.com/shirou/gopsutil/host"
	"github.com/spf13/cobra"
)

var info, _ = host.Info()
var collectCmd = &cobra.Command{
	Use:   "collect",
	Short: "collect the OS info",
	Long:  "",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Printf("OS: %v", info.OS)
		fmt.Printf("platform: %v", info.Platform)
		fmt.Printf("family: %v", info.PlatformFamily)
		fmt.Printf("version: %v", info.PlatformVersion)
	},
}

func init() {
	rootCmd.AddCommand(collectCmd)
}

```

**Expected behavior**
execute `go build` successfully

**Environment (please complete the following information):**
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`]
```
// sw_vers
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

// uname -a
Darwin alexcdever.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Additional context**
```
// go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alexcdever/Library/Caches/go-build"
GOENV="/Users/alexcdever/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/alexcdever/.gvm/pkgsets/go1.16/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alexcdever/.gvm/pkgsets/go1.16/global"
GOPRIVATE=""
GOPROXY="https://goproxy.cn/,direct"
GOROOT="/Users/alexcdever/.gvm/gos/go1.16"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/alexcdever/.gvm/gos/go1.16/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cm/gpfzcmkx6y36q_56gzzkd_sr0000gn/T/go-build3970990871=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by Lomanic** [comment] 2021-02-25 17:34
Duplicate of #921, update `golang.org/x/unix`.

You probably wouldn't have this issue if you were using the module-aware packages, with v3 in their path: https://godocs.io/github.com/shirou/gopsutil/v3

**Closed by Lomanic** 2021-02-25 17:34 UTC

**Comment by voronindev** [comment] 2021-02-26 09:41
Hello, still doesn't works. I've replaced but have the same problems with v3 version:
```GOROOT=/usr/local/Cellar/go/1.16/libexec #gosetup
GOPATH=/Users/voronindev/go #gosetup
/usr/local/Cellar/go/1.16/libexec/bin/go build -i -o /private/var/folders/g_/1w6vddrs17x6qj158dbmcmsc0000gn/T/___go_run_provider gitlab.wvservices.com/waves/gateways/gw-provider-eth/cmd #gosetup
go build: -i flag is deprecated
# github.com/shirou/gopsutil/cpu
../../../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.1+incompatible/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.```

**Comment by voronindev** [comment] 2021-02-26 09:42
Hello, still doesn't works. I've replaced but have the same problems with v3 version
```
GOROOT=/usr/local/Cellar/go/1.16/libexec #gosetup
GOPATH=/Users/developer/go #gosetup
/usr/local/Cellar/go/1.16/libexec/bin/go build -i -o /private/var/folders/g_/1w6vddrs17x6qj158dbmcmsc0000gn/T/___go_run_provider cmd #gosetup
go build: -i flag is deprecated
# github.com/shirou/gopsutil/cpu
../../../../go/pkg/mod/github.com/shirou/gopsutil@v3.21.1+incompatible/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.
```

**Comment by Lomanic** [comment] 2021-02-28 23:52
@voronindev this is not the same issue but #976
