### ISSUE TITLE
Process.Cmdline() is rising memory on windows

### ISSUE THREAD

**Issue by hoaidanh** [shirou/gopsutil#608] opened 2018-11-16 09:08 UTC
There is my code

```
processArray, err := process.Processes()
for _, item := range processArray {
		
		cmd,_ := item.Cmdline()  //rising memory
		//do something
}

```
I check memory, it rising memory so fast, and item.Cmdline() is the cause, you can see in the picture

![capture1](https://user-images.githubusercontent.com/37470966/48612900-d87d1680-e9bc-11e8-8090-147bfa04ec01.PNG)

**Comment by Lomanic** [comment] 2018-11-16 11:09
Yet another duplicate of #250. 

Please follow issue templates so we don't have to guess which platform you are using from a screenshot.

**Closed** 2018-11-16 11:10 UTC
Labels: os:windows, package:process
