### ISSUE TITLE
Telegraf reports error on FreeBSD while fetching swap statistics

### ISSUE THREAD

**Issue by jayshah11** [shirou/gopsutil#830] opened 2020-02-03 17:44 UTC
I am using Telegraf 1.12.1_1 on FreeBSD 11.3. Telegraf reports the following error:

[inputs.swap] Error in plugin: error getting swap memory info: no swap devices found

I am assuming telegraf uses mem_freebsd.go to measure swap stats but I fail to understand why it report an error. It looks like it uses vmstat

**Comment by Lomanic** [comment] 2020-02-03 18:30
What's the result of `sysctl vm.nswapdev`on your FreeBSD machine? Error comes from [this line](https://github.com/shirou/gopsutil/blob/33820ab93048c0de8edf2a8d72c102badc508424/mem/mem_freebsd.go#L121) and checks for the result of an equivalent as this command.

**Comment by jayshah11** [comment] 2020-02-03 20:06
0

**Comment by Lomanic** [comment] 2020-02-03 23:57
Looks like you don't have any swap devices on this host then. Check this out with `swapctl -l`, look at `/etc/fstab`, `sysctl -a | grep swap`…

**Comment by Lomanic** [comment] 2020-02-09 22:57
Closing as it's working as intended

**Closed** 2020-02-09 22:57 UTC
Labels: os:freebsd, package:mem
