### ISSUE TITLE
[Windows] cpu.Info() timing out

### ISSUE THREAD

**Issue by FlorinAsavoaie** [shirou/gopsutil#469] opened 2017-12-11 13:22 UTC
In `github.com/shirou/gopsutil/internal/common`, there is a Timeout hardcoded for the WMI queries. When the CPU is busy, `cpu.Info()` (and maybe other stuff as well) is failing as the WMI is taking too long to respond to the query. I would expect to be able to pass this Timeout from my code.

**Comment by vrecan** [comment] 2017-12-11 21:59
I've run into this a few times as well. It would be nice to be able to pass in the context timeouts or set them in some way.

**Comment by shirou** [comment] 2017-12-19 08:26
I have added plan to v3 (#362) about `WithContext` method.

**Comment by sadag** [comment] 2018-02-12 21:51
Please review PR #488

**Comment by Lomanic** [comment] 2022-10-23 00:46
Closing as a duplicate of #394 (as always, WMI calls should be avoided)

**Closed by Lomanic** 2022-10-23 00:46 UTC
Labels: os:windows, package:cpu
