### ISSUE TITLE
Internal call not allowed

### ISSUE THREAD

**Issue by Wiifou** [shirou/gopsutil#1020] opened 2021-01-12 14:20 UTC
**Description**
When i run my main this error apear :
use of internal package github.com/shirou/gopsutil/internal/common not allowed

**To Reproduce**
I import "github.com/shirou/gopsutil/internal/common"

and when i run  my main the error pop.

I'm trying to list every running process and display their PID, PPID, running time and other info 

**Environment :**
 - [ ] Linux:
 - [ ] NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal 

`Linux maelPC 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Lomanic** [comment] 2021-01-12 18:37
That's the point of internal packages, they are not available for public consumption. Use the functions in the [`process` package](https://godoc.org/github.com/shirou/gopsutil/v3/process). Duplicate of #580.

**Closed by Lomanic** 2021-01-12 18:37 UTC
