### ISSUE TITLE
Warning of IOMasterPort on MacOS 12.0

### ISSUE THREAD

**Issue by h3n4l** [shirou/gopsutil#1222] opened 2022-01-06 15:36 UTC
**Describe the bug**
I use `github.com/shirou/gopsutil v3.20.10+incompatible` at`go.mod` in my project, it will report waring likes below when I build my project:
```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
```
**To Reproduce**
Using this version on MacOS 12.0 will reproduce it

**Expected behavior**
I expected no warning.

**Environment (please complete the following information):**
 - [ ] Mac OS:
 `sw_vers`:
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559  
`uname -a`:
Darwin h3n4ldeMacBook-Pro.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Comment by Lomanic** [comment] 2022-01-06 23:13
Duplicate of #1164

**Closed by Lomanic** 2022-01-06 23:13 UTC
