### ISSUE TITLE
High cpu on unoptimized code in process package

### ISSUE THREAD

**Issue by gnud** [shirou/gopsutil#1343] opened 2022-08-19 11:28 UTC
**Describe the bug**
I am going to produce process monitoring app to find which process is increasing the temperature, but I ended up producing high cpu (over 80%), can this be optimized to run in realtime and not produce much cpu?

**To Reproduce**
```go
	processes, err := process.Processes()
	if err != nil {
		return
	}

	for true {
		time.Sleep(1000 * 5)

		for _, _process := range processes {
			var totalCpu, _ = _process.CPUPercent()
			if totalCpu < 30 {
				continue
			}

			fmt.Printf(
				"%d,%s,%f\n",
				_process.Pid,
				getOne(_process.Name()),
				getOne(_process.CPUPercent()),
			)
		}
	}
```

**Expected behavior**
Smooth realtime recording/printing.

**Environment (please complete the following information):**
 - [x] Linux:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

`Linux damjan 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Lomanic** [comment] 2022-10-23 15:04
This is a duplicate of #842, #1283 and #1070

**Closed by Lomanic** 2022-10-23 15:04 UTC
Labels: package:process, performance
