### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by chengfeiZhou** [shirou/gopsutil#1312] opened 2022-06-07 07:49 UTC
**Describe the bug**
When I was building the project, `github.com/shirou/gopsutil/disk` went error!

**To Reproduce**
```
 ->: go run main.go server -c=config/settings.dev.133.yml
# github.com/shirou/gopsutil/disk
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.7+incompatible/disk/disk_darwin.go:67:51: cannot use stat.Mntfromname[:] (value of type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.7+incompatible/disk/disk_darwin.go:68:49: cannot use stat.Mntonname[:] (value of type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.7+incompatible/disk/disk_darwin.go:69:50: cannot use stat.Fstypename[:] (value of type []byte) as type []int8 in argument to common.IntToString
../../../go/pkg/mod/github.com/shirou/gopsutil@v2.20.7+incompatible/disk/disk_darwin.go:85:43: cannot use stat.Fstypename[:] (value of type []byte) as type []int8 in argument to common.IntToString
```

**Environment (please complete the following information):**
 - [x] Mac OS: [paste the result of `sw_vers` and `uname -a`
```
sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

uname -a
Darwin zcf-MBP.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
```

**Additional context**
```
go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/chengfei/Library/Caches/go-build"
GOENV="/Users/chengfei/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/chengfei/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/chengfei/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="0"
GOMOD="/Users/chengfei/Documents/Project/fofa_admin/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kc/l95glwlx7tjbhb147h6j6x5m0000gn/T/go-build1193603499=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by Lomanic** [comment] 2022-06-07 17:37
Duplicate of #958

You're using an obsolete gopsutil 2020 release. You have to update the library.

**Closed by Lomanic** 2022-06-07 17:37 UTC
