### ISSUE TITLE
func Processes() ([]*Process, error) can pass parameters

### ISSUE THREAD

**Issue by NadamHL** [shirou/gopsutil#918] opened 2020-08-12 09:02 UTC
func Processes() ([]*Process, error) This function, whether it is possible to pass parameters, once called, will collect all the process information of the system, which consumes more CPU, if you can selectively collect process information, it will be more it is good. Hope to adopt
**Additional context**
[Add any other context or screenshots about the feature request here.]

**Comment by Lomanic** [comment] 2020-08-12 10:38
Duplicate of #286.

**Closed** 2020-08-12 10:38 UTC
Labels: package:process
