### ISSUE TITLE
Get process sorted with cpu,mem,disk like "top"

### ISSUE THREAD

**Issue by linker0512** [shirou/gopsutil#860] opened 2020-04-21 02:59 UTC
Dearsir,I am a rookie developer, recently used gopsutil to do some monitoring, gopsutil is very useful and very helpful to me, I hope that in the future gopsutil can provide some process sorting function similar to "top"

**Comment by Lomanic** [comment] 2020-04-21 19:07
duplicate of #374, gopsutil won't provide this kind of function

**Closed by Lomanic** 2020-04-21 19:07 UTC
