### ISSUE TITLE
Issue with Mountpoint field of PartitionStat if mounting path has space in it

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#555] opened 2018-07-17 20:36 UTC
On Linux, if a partition mount path has a space in it, then the string in the PartitionStat returned by disk.Partitions() replaces that space with the string "\040" (not the character).

**Comment by Lomanic** [comment] 2018-07-19 17:06
Confirmed, can reproduce, see commit above for a quick and incomplete fix, but which is sufficient for your issue. I will provide a proper and better fix in the coming days.

**Comment by cjbassi** [comment] 2018-11-15 18:19
I'm actually still getting this error when using the last commit from master.

**Comment by Lomanic** [comment] 2018-11-16 10:16
Indeed, I only fixed it for `UsageStat`s returned by `disk.Usage`. Will be fixed this weekend.

**Comment by slorenzo** [comment] 2019-09-01 01:06
@Lomanic I think it should be reopened since this issue persist in some use cases. I guess this is one of those: https://github.com/shirou/gopsutil/blob/ffb381dc5de803fb8985813d13d49b76c79d453a/disk/disk_linux.go#L292

In the meantime, a possible workaround to avoid this issue is using [unescapeFstab](https://github.com/shirou/gopsutil/blob/381f7cc0bf4ccb60157fd5c6eaabfdfc681e6c2f/disk/disk_unix.go#L62) to normalize the output.

**Comment by Lomanic** [comment] 2019-09-01 08:19
Will check on an old <2.6.26 kernel.

**Closed** 2019-09-01 11:28 UTC
Labels: os:linux, package:disk
