### ISSUE TITLE
mac build error

### ISSUE THREAD

**Issue by iwalkerr** [shirou/gopsutil#986] opened 2020-11-05 08:55 UTC
<img width="1255" alt="Xnip2020-11-05_16-54-15" src="https://user-images.githubusercontent.com/43042929/98219237-b4d78000-1f87-11eb-858c-c08d67645e49.png">

System version MacBook Pro (15-inch, 2016)

**Comment by sakal** [comment] 2020-11-05 10:05
I have this issue too on 2.10.8, 2.10.9 and problem disappeared on 3.10.8

**Comment by Lomanic** [comment] 2020-11-05 17:18
Quite a duplicate of #958, update `golang.org/x/sys` (`go get -u golang.org/x/sys`). Wasn't one of the selling points to have converted gopsutil to go modules and having go.mod and go.sum files (as nobody cared about `dep` and its Gopkg.lock) to solve this kind of issues?

**Comment by iwalkerr** [comment] 2020-11-07 02:33
> 与[＃958](https://github.com/shirou/gopsutil/issues/958)相当，更新`golang.org/x/sys`（`go get -u golang.org/x/sys`）。难道不是将gopsutil转换为go模块并拥有go.mod和go.sum文件（没人关心的`dep`及其Gopkg.lock）来解决此类问题的卖点之一吗？
> 
> PS：请不要张贴文本的屏幕截图，没有人可以使用带有图像的搜索引擎或复制其内容

ok,thanks

**Comment by iwalkerr** [comment] 2020-11-07 02:38
> 我在2.10.8、2.10.9上也遇到了这个问题，而在3.10.8上问题就消失了

thanks

**Closed** 2020-11-07 17:07 UTC
Labels: os:darwin, package:disk
