### ISSUE TITLE
Find process by name

### ISSUE THREAD

**Issue by mbrostami** [shirou/gopsutil#565] opened 2018-08-03 16:45 UTC
How can I find a process with the name?

**Comment by Lomanic** [comment] 2018-08-03 18:07
Just iterate over each Process returned by [process.Processes()](https://godoc.org/github.com/shirou/gopsutil/process#Processes) and check the result of [Name()](https://godoc.org/github.com/shirou/gopsutil/process#Name). 

Almost a duplicate of #463.

**Closed** 2018-08-03 18:09 UTC
Labels: package:process, question
