### ISSUE TITLE
IOMasterPort is deprecated

### ISSUE THREAD

**Issue by CaledoniaProject** [shirou/gopsutil#1350] opened 2022-09-11 23:10 UTC
I'm running gopsutil on MacOS 12.5.1, and gopsutil 3.21.9

```
github.com/shirou/gopsutil/v3 v3.21.9
```

And I got a warning:

```
# github.com/shirou/gopsutil/v3/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
```

**Comment by Lomanic** [comment] 2022-09-14 09:18
It's the 5th duplicate of https://github.com/shirou/gopsutil/issues/1164

Update gopsutil.

**Closed by Lomanic** 2022-09-14 09:18 UTC
