### ISSUE TITLE
Getting all processes executable with process.Exe() is slow

### ISSUE THREAD

**Issue by Highter87** [shirou/gopsutil#586] opened 2018-09-14 11:27 UTC
Hello Friend!

This code is very long executable time - 9 seconds:

```
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/process"
)

func main() {
	procList, _ := process.Processes()

	for _, proc := range procList {
		cmdLine, _ := proc.Exe()

		fmt.Println(cmdLine)
	}
}
```

Can you optimize it method?

**Comment by Lomanic** [comment] 2018-09-14 13:39
Tell us which platform you are running this code on, gopsutil runs on many OSes and architectures with code differing (sometimes drastically) between them.

**Comment by Highter87** [comment] 2018-09-14 13:51
Oh... sorry friend. I Use Windows 10, core i5 5th gen. And go version go1.10.4 windows/amd64

**Comment by Lomanic** [comment] 2018-09-14 14:00
Closing as duplicate of #250, root cause is the slow wmi requests executed for each process found. Help to migrate from wmi calls would be appreciated a lot.

**Closed** 2018-09-14 14:00 UTC
Labels: os:windows, package:process

**Comment by Highter87** [comment] 2018-09-16 09:11
Algoritm is not difficult.
When calling process.Processes() you open gourutine with execute this:
`WMIC process GET Caption,ProcessId,Commandline /format:csv`
You can see all type format output this url (https://www.vanstechelman.eu/windows/wmic/output_formats)

set variable output, parse csv, and compare/set with output your process.Processes() method

This method veryyyy fast than every times get commandLine by calling
