### ISSUE TITLE
What's the fastest/idiomatic way to search for processes by name?

### ISSUE THREAD

**Issue by xeijin** [shirou/gopsutil#1069] opened 2021-05-09 14:50 UTC
I'm fairly new to golang so perhaps there is a better way, but I am finding the below function quite slow (5-10 seconds) on macOS with few other processes started. Any thoughts?

```golang

import (
	psutilProc "github.com/shirou/gopsutil/v3/process"
	"strings"
	"log"
)

func DiscoverEmacsProcs() (emacsProcs []*EmacsInstance) {

	var procs []*psutilProc.Process // all current system procs

	log.Printf("retrieving a list of system processes...")
	procs, _ = psutilProc.Processes()

	for _, proc := range procs {

		instance := &EmacsInstance{proc: proc}
		instance.pid = proc.Pid
		instance.name, _ = proc.Name()
		instance.cmd, _ = proc.Cmdline()
		instance.bg, _ = proc.Background()
		instance.fg, _ = proc.Foreground()

		if strings.Contains(strings.ToLower(instance.name), "emacs") {
			emacsProcs = append(emacsProcs, instance)
		}
	}

	return
}

func main() {
	DiscoverEmacsProcs()
}
```

**Comment by Lomanic** [comment] 2021-05-11 17:01
For the moment in gopsutil there's not a faster way (duplicate of #565). You could probably optimize your code like this so you don't waste time getting processes attributes for processes you're not interested in.

```go
func DiscoverEmacsProcs() (emacsProcs []*EmacsInstance) {

	var procs []*psutilProc.Process // all current system procs

	log.Printf("retrieving a list of system processes...")
	procs, _ = psutilProc.Processes()

	for _, proc := range procs {

		instance := &EmacsInstance{proc: proc}
		instance.pid = proc.Pid
		instance.name, _ = proc.Name()
		
		if strings.Contains(strings.ToLower(instance.name), "emacs") {
			instance.cmd, _ = proc.Cmdline()
			instance.bg, _ = proc.Background()
			instance.fg, _ = proc.Foreground()

			emacsProcs = append(emacsProcs, instance)
		}
	}

	return
}
```

**Closed by Lomanic** 2021-05-11 17:01 UTC
