### ISSUE TITLE
undefined: "golang.org/x/sys/windows".EnumProcesses

### ISSUE THREAD

**Issue by sjt-xfwh** [shirou/gopsutil#835] opened 2020-02-10 15:58 UTC
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:174:13: undefined: "golang.org/x/sys/windows".EnumProcesses
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:212:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:281:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:384:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:448:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:494:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:798:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:813:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION
..\..\pkg\mod\github.com\shirou\gopsutil@v2.20.1+incompatible\process\process_windows.go:847:32: undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION

**Comment by sjt-xfwh** [comment] 2020-02-10 15:58
on windows 10

**Comment by Lomanic** [comment] 2020-02-10 17:06
Duplicate of #743.

**Closed by Lomanic** 2020-02-10 17:06 UTC

**Comment by e9571** [comment] 2020-10-21 03:55
update new golang.org\x\sys

**Comment by e9571** [comment] 2020-10-21 03:56
https://github.com/golang/sys
