### ISSUE TITLE
DiskIOCounters returns invalid numbers and blocks for 500ms on windows

### ISSUE THREAD

**Issue by vrecan** [shirou/gopsutil#72] opened 2015-09-05 01:07 UTC
When using the diskIOCounters I am seeing really strange behavior. 

* Read and Write counts are frequently negative numbers.
* Blocks for 500ms (linux version doesn't block at all)
* Is missing byte throughput numbers

**Comment by shirou** [comment] 2015-09-05 12:56
To get DiskIOCounter on windows, it use performance counter. It needs block to gather counters. Negative numbers are curious. I will look for another way to get disk io counter. please be patient.

**Comment by shirou** [comment] 2015-09-17 08:19
Oh, I have not replied this. I have changed the implementation of DiskIOCounter to use wmi from performance counter at 773d9d3caa6e775585eb3b893d4ec5feaf6c39eb. So, the value becomes more accurate and block is reduced. Please check it again.

**Comment by shirou** [comment] 2015-10-19 02:01
I close this issue.  If the problem is not resolved or something happen, feel free to reopen or open a new issue. Thank you.

**Closed by shirou** 2015-10-19 02:01 UTC
