### ISSUE TITLE
（Linux OS）Compile failed 

### ISSUE THREAD

**Issue by ieczw** [shirou/gopsutil#815] opened 2020-01-10 02:14 UTC
**Describe the bug**
```
../vendor/github.com/shirou/gopsutil/process/process_linux.go:312:21: undefined: Data
../vendor/github.com/shirou/gopsutil/process/process_linux.go:314:21: undefined: Stack
../vendor/github.com/shirou/gopsutil/process/process_linux.go:316:21: undefined: RSS
../vendor/github.com/shirou/gopsutil/process/process_linux.go:324:21: undefined: Locked
../vendor/github.com/shirou/gopsutil/process/process_linux.go:326:21: undefined: VMS
../vendor/github.com/shirou/gopsutil/process/process_linux.go:330:14: undefined: PendingProcess
../vendor/github.com/shirou/gopsutil/process/process_linux.go:362:9: undefined: numCtxSwitches
../vendor/github.com/shirou/gopsutil/process/process_linux.go:367:9: undefined: NumFDsWithContext
../vendor/github.com/shirou/gopsutil/process/process_linux.go:377:9: undefined: NumThreadsWithContext
../vendor/github.com/shirou/gopsutil/process/process_linux.go:385:9: undefined: numThreads
../vendor/github.com/shirou/gopsutil/process/process_linux.go:385:9: too many errors
```

**Expected behavior**
Compile failed

**Environment (please complete the following information):**
```
Linux TENCENT64.site 3.10.104-1-tlinux2-0041.tl2 #1 SMP Fri Oct 28 20:58:27 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
go version go1.13.5 linux/amd64

**Comment by Lomanic** [comment] 2020-01-16 23:55
I don't have any way to reproduce, check you have vendored properly all the files maybe.Try running the tests also.

**Comment by shirou** [comment] 2020-05-16 07:32
Since there is no updates, I close this issue. Feel free to re-open.

**Closed by shirou** 2020-05-16 07:32 UTC
Labels: os:linux, package:process
