### ISSUE TITLE
cpu.Percents() returns 6 values on 4 core system

### ISSUE THREAD

**Issue by cjbassi** [shirou/gopsutil#569] opened 2018-08-15 01:48 UTC
Second comment at cjbassi/gotop#29

I'm getting the same issue on my Windows system. Windows 10, i5-2500k. cpu.Count returns the corrent number of cores but cpu.Percents is off.

**Comment by Lomanic** [comment] 2018-08-15 09:37
Duplicate of https://github.com/shirou/gopsutil/issues/551

**Closed** 2018-08-15 09:38 UTC
