### ISSUE TITLE
github.com/shirou/gopsutil/process error with /golang.org/x/sys/windows

### ISSUE THREAD

**Issue by LeoLee98** [shirou/gopsutil#873] opened 2020-05-14 07:22 UTC

**Comment by LeoLee98** [comment] 2020-05-14 07:22
undefined: "golang.org/x/sys/windows".EnumProcesses
undefined: "golang.org/x/sys/windows".PROCESS_QUERY_LIMITED_INFORMATION

**Comment by LeoLee98** [comment] 2020-05-14 07:23
GOOS=windows

**Comment by shirou** [comment] 2020-05-16 07:47
What golang version are you using? `EnumProcesses` is introduced from this [commit](https://github.com/golang/sys/commit/e8c54fb511f6a2d695a4403ae0dab1c05aef011a), so golang 1.14 is required for windows I think.

**Comment by Lomanic** [comment] 2020-05-16 09:34
Duplicate of #743. See https://github.com/shirou/gopsutil/issues/743#issuecomment-519241791

The /x packages are unrelated to the Go version, they are just like other 3rd-party packages in this regard.

**Closed** 2020-05-16 09:34 UTC
